### ISSUE TITLE
Functional Components & Why?

### ISSUE THREAD

**Issue by ashmalzahra** [ashmalzahra/math-magicians#4]
### Why functional components over class-based ones?
 - **Classes are bigger**
   - Functional components are smaller. In terms of file size, this may seem insignificant in smaller projects, but in larger applications, this can result in a decent reduction in bundle size, which will improve the performance of your application.
 - **Combine code in a meaningful way**
   - In classes, things that should be tied together are forced to be split apart, and things that should be split apart are forced together. 
 - **Reusing stateful logic across components**
   - Class components often require lots of nesting or using mixins, and in some cases, code has to be repeated.

_As of React v16.8 it's recommended to only write functional components. You might see class components every once in a while, but using them is discouraged. Which is why my project is built using functional components only. Even in this small application, using functional components has lowered the file sizes and improved the readability of the application. If you'd like to look further, you can find the current version of the app [here](https://github.com/ashmalzahra/math-magicians)_

**Comment by franclobo** [comment]
Hi @ashmalzahra, 

# STATUS: APPROVED 😃 

![gif-good-job-79](https://user-images.githubusercontent.com/58642949/219819543-bd0fbe1c-456d-4e13-ac5a-46e37716c044.gif)

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
- Good use of hooks ✔️ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
